apiVersion: v2
name: opentelemetry-collector
version: 0.2.2
description: Log10x enhanced OpenTelemetry Collector Helm chart for Kubernetes
type: application
home: https://github.com/log-10x/opentelemetry-helm-charts
sources:
  - https://github.com/log-10x/opentelemetry-helm-charts
  - https://github.com/open-telemetry/opentelemetry-collector
  - https://github.com/open-telemetry/opentelemetry-collector-contrib
maintainers:
  - name: Log10x
    email: engineering@log10x.com
icon: https://raw.githubusercontent.com/log-10x/opentelemetry-helm-charts/main/icon.png
appVersion: 0.144.0
keywords:
  - opentelemetry
  - otel-collector
  - log10x
  - logging
  - observability
  - log-optimization
